"""workouts sequence_number nullable

Revision ID: 1da80ad3f1df
Revises: ba89f46f0c83
Create Date: 2026-08-08 12:34:30.312341

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1da80ad3f1df'
down_revision: str | None = 'ba89f46f0c83'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'sequence_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'sequence_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
