"""pending payments and tribute source

Revision ID: 6dbcfb436c46
Revises: 1da80ad3f1df
Create Date: 2026-08-08 19:35:31.248656

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6dbcfb436c46'
down_revision: str | None = '1da80ad3f1df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # autogenerate не отслеживает новые значения существующих Postgres ENUM
    # (ALTER TYPE ... ADD VALUE) — добавляем вручную. Поддерживается внутри
    # транзакции с PG12+, но само значение нельзя ИСПОЛЬЗОВАТЬ в той же
    # транзакции, где его добавили — здесь мы его только объявляем.
    op.execute("ALTER TYPE subscription_source ADD VALUE IF NOT EXISTS 'tribute'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('tribute', name='pending_payment_provider'), nullable=False),
    sa.Column('external_order_id', sa.Text(), nullable=False),
    sa.Column('days', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', name='pending_payment_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_payments_user_id'), 'pending_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_payments_user_id'), table_name='pending_payments')
    op.drop_table('pending_payments')
    # ### end Alembic commands ###

    # autogenerate не выписывает DROP TYPE для нативных Postgres ENUM (см.
    # тот же приём в первой миграции) — без этого повторный upgrade падает
    # на "type already exists".
    op.execute("DROP TYPE IF EXISTS pending_payment_status")
    op.execute("DROP TYPE IF EXISTS pending_payment_provider")

    # А вот у subscription_source Postgres не поддерживает удаление ОДНОГО
    # значения ENUM (только пересоздание типа целиком) — 'tribute' остаётся
    # и на downgrade. Безвредно: раз pending_payments уже удалена, новых
    # строк subscriptions с этим source взяться неоткуда.
