"""initial schema

Revision ID: ba89f46f0c83
Revises: 
Create Date: 2026-08-08 12:30:36.420143

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ba89f46f0c83'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('branch', sa.Enum('band', 'assisted', name='branch'), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_status', sa.Enum('none', 'trial', 'active', 'expired', name='subscription_status'), server_default='none', nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coins_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('achievements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_achievements_user_code')
    )
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('baselines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('branch_result', sa.Enum('band', 'assisted', name='branch'), nullable=False),
    sa.Column('equipment_type', sa.Enum('band', 'weight', name='equipment_type'), nullable=False),
    sa.Column('band_thickness_mm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reps', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baselines_user_id'), 'baselines', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('none', 'trial', 'active', 'expired', name='subscription_status'), nullable=False),
    sa.Column('source', sa.Enum('trial', 'stars', 'coins', 'admin_grant', name='subscription_source'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('coins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('workout_completed', 'achievement_unlocked', 'subscription_extension', 'admin_adjustment', name='coin_reason'), nullable=False),
    sa.Column('related_achievement_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coins_user_id'), 'coins', ['user_id'], unique=False)
    op.create_table('workout_sets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('started_from_baseline_id', sa.BigInteger(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('workouts_completed', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='workout_set_status'), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['started_from_baseline_id'], ['baselines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'set_number', name='uq_workout_sets_user_set_number')
    )
    op.create_index(op.f('ix_workout_sets_user_id'), 'workout_sets', ['user_id'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('workout_set_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('started', 'completed', name='workout_status'), server_default='started', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_set_id'], ['workout_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sequence_number', deferrable=True, initially='DEFERRED', name='uq_workouts_user_sequence_number')
    )
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    op.create_index(op.f('ix_workouts_workout_set_id'), 'workouts', ['workout_set_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('block_type', sa.Enum('a', 'b', name='block_type'), nullable=False),
    sa.Column('working_reps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_reps', sa.SmallInteger(), nullable=False),
    sa.Column('target_before', sa.SmallInteger(), nullable=False),
    sa.Column('target_after', sa.SmallInteger(), nullable=False),
    sa.Column('equipment_changed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('band_thickness_mm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'block_type', name='uq_blocks_workout_block_type')
    )
    op.create_index(op.f('ix_blocks_workout_id'), 'blocks', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocks_workout_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_workouts_workout_set_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_workout_sets_user_id'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_coins_user_id'), table_name='coins')
    op.drop_table('coins')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_baselines_user_id'), table_name='baselines')
    op.drop_table('baselines')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # autogenerate не выписывает DROP TYPE для нативных Postgres ENUM —
    # без этого повторный upgrade падает на "type already exists".
    for enum_name in (
        'block_type', 'coin_reason', 'subscription_source', 'workout_status',
        'workout_set_status', 'subscription_status', 'equipment_type', 'branch',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
